apiVersion: v1
kind: Service
metadata:
  name: velero-watchdog-clusterip
  namespace: velero-ui
spec:
  selector:
    app: velero-watchdog
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
