apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-watchdog-config
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
data:
  BACKUP_ENABLED: {{ .Values.watchdogConfig.backupEnable | quote }}
  EMAIL_ACCOUNT: {{ .Values.watchdogConfig.emailAccount | quote }}
  EMAIL_ENABLE: {{ .Values.watchdogConfig.emailEnable | quote }}
  EMAIL_PASSWORD: {{ .Values.watchdogConfig.emailPassword | quote }}
  EMAIL_RECIPIENTS: {{ .Values.watchdogConfig.emailRecipients | quote }}
  EMAIL_SMTP_PORT: {{ .Values.watchdogConfig.emailSmtpPort | quote }}
  EMAIL_SMTP_SERVER: {{ .Values.watchdogConfig.emailSmtpServer | quote }}
  EXPIRES_DAYS_WARNING: {{ .Values.watchdogConfig.expiresDaysWarning | quote }}
  K8S_IN_CLUSTER_MODE: {{ .Values.watchdogConfig.k8SInclusterMode | quote }}
  PROCESS_CLUSTER_NAME: {{ .Values.watchdogConfig.processClusterName | quote }}
  PROCESS_CYCLE_SEC: {{ .Values.watchdogConfig.processCycleSec | quote }}
  SCHEDULE_ENABLED: {{ .Values.watchdogConfig.scheduleEnable | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.watchdogConfig.telegramChatId | quote }}
  TELEGRAM_ENABLE: {{ .Values.watchdogConfig.telegramEnable | quote }}
  TELEGRAM_TOKEN: {{ .Values.watchdogConfig.telegramToken | quote }}