apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-watchdog
  labels:
    app: velero-watchdog
    tier: backend
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.watchdog.replicas }}
  selector:
    matchLabels:
      tier: backend
    {{- include "seriohub-velero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: velero-watchdog
        tier: backend
      {{- include "seriohub-velero.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "seriohub-velero.fullname" . }}-watchdog-config
        image: {{ .Values.watchdog.veleroMonitoring.image.repository }}:{{ .Values.watchdog.veleroMonitoring.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.watchdog.veleroMonitoring.imagePullPolicy }}
        name: velero-monitoring
        resources: {{- toYaml .Values.watchdog.veleroMonitoring.resources | nindent 10
          }}
      serviceAccountName: {{ include "seriohub-velero.fullname" . }}-k8s-read-only-service-account